package Libro.cap02.exepciones;

public class TestLogin {
  /*  public static void main(String[] args)
 {
 try
 {
 Aplication app = new Aplication();
 // intento el login
 Usuario u = app.login("juan","juan123sito");
 // muestro el resultado
 System.out.println(u);
 }
 catch(Exception ex)
 {
 // ocurrio un error
 System.out.print("Servicio temporalmente interrumpido: ");
 System.out.println(ex.getMessage());
 }
 }*/
   /* public static void main(String[] args)
 {
 try
 {
 Aplicacion app = new Aplicacion();
 Usuario u = app.login("juan","juan123sito");
 System.out.println(u);
 }
 catch(ErrorFisicoException ex)
 {
 // ocurrio un error
 System.out.print("Servicio temporalmente interrumpido: ");
 System.out.println( ex.getMessage() );
 }
 }*/
}
